# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/howard/single-cycle-mips-cpu/single-cycle-mips-cpu.cache/wt [current_project]
set_property parent.project_path /home/howard/single-cycle-mips-cpu/single-cycle-mips-cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/howard/single-cycle-mips-cpu/single-cycle-mips-cpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/howard/single-cycle-mips-cpu/src/ALU.v
  /home/howard/single-cycle-mips-cpu/src/ALU_control.v
  /home/howard/single-cycle-mips-cpu/src/background_engine.v
  /home/howard/single-cycle-mips-cpu/src/bcd_7seg.v
  /home/howard/single-cycle-mips-cpu/src/bg_rom.hex.v
  /home/howard/single-cycle-mips-cpu/src/clock_div.v
  /home/howard/single-cycle-mips-cpu/src/cpu.v
  /home/howard/single-cycle-mips-cpu/src/cpu_control.v
  /home/howard/single-cycle-mips-cpu/src/data_mem.v
  /home/howard/single-cycle-mips-cpu/single-cycle-mips-cpu.srcs/sources_1/new/debouncer.v
  /home/howard/single-cycle-mips-cpu/src/debug_screen.v
  /home/howard/single-cycle-mips-cpu/src/display.v
  /home/howard/single-cycle-mips-cpu/src/inst_mem.v
  /home/howard/single-cycle-mips-cpu/src/ram.v
  /home/howard/single-cycle-mips-cpu/src/reg_file.v
  /home/howard/single-cycle-mips-cpu/src/seg_mux.v
  /home/howard/single-cycle-mips-cpu/src/vga_sync.v
  /home/howard/single-cycle-mips-cpu/src/vga_test.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/howard/single-cycle-mips-cpu/mips-cpu-basys3.xdc
set_property used_in_implementation false [get_files /home/howard/single-cycle-mips-cpu/mips-cpu-basys3.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top vga_display -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vga_display.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file vga_display_utilization_synth.rpt -pb vga_display_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
